// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _toGray_HH_
#define _toGray_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "toGray_Block_proc.h"
#include "toGray_AXIvideo2Mat.h"
#include "toGray_CvtColor.h"
#include "toGray_Equalize.h"
#include "toGray_Mat2AXIvideo_8_1080_1920_0_s.h"
#include "FIFO_toGray_inMat_rows_V_channel.h"
#include "FIFO_toGray_inMat_rows_V_channel1.h"
#include "FIFO_toGray_inMat_cols_V_channel.h"
#include "FIFO_toGray_inMat_cols_V_channel1.h"
#include "FIFO_toGray_grayMat_rows_V.h"
#include "FIFO_toGray_grayMat_cols_V.h"
#include "FIFO_toGray_outMat_rows_V.h"
#include "FIFO_toGray_outMat_cols_V.h"
#include "FIFO_toGray_inMat_data_stream_0_V.h"
#include "FIFO_toGray_inMat_data_stream_1_V.h"
#include "FIFO_toGray_inMat_data_stream_2_V.h"
#include "FIFO_toGray_grayMat_data_stream_0_V.h"
#include "FIFO_toGray_outMat_data_stream_0_V.h"

namespace ap_rtl {

struct toGray : public sc_module {
    // Port declarations 26
    sc_in< sc_lv<24> > IN_STREAM_TDATA;
    sc_in< sc_lv<3> > IN_STREAM_TKEEP;
    sc_in< sc_lv<3> > IN_STREAM_TSTRB;
    sc_in< sc_lv<1> > IN_STREAM_TUSER;
    sc_in< sc_lv<1> > IN_STREAM_TLAST;
    sc_in< sc_lv<1> > IN_STREAM_TID;
    sc_in< sc_lv<1> > IN_STREAM_TDEST;
    sc_out< sc_lv<8> > OUT_STREAM_TDATA;
    sc_out< sc_lv<1> > OUT_STREAM_TKEEP;
    sc_out< sc_lv<1> > OUT_STREAM_TSTRB;
    sc_out< sc_lv<1> > OUT_STREAM_TUSER;
    sc_out< sc_lv<1> > OUT_STREAM_TLAST;
    sc_out< sc_lv<1> > OUT_STREAM_TID;
    sc_out< sc_lv<1> > OUT_STREAM_TDEST;
    sc_in< sc_lv<32> > cols;
    sc_in< sc_lv<32> > rows;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > IN_STREAM_TVALID;
    sc_out< sc_logic > IN_STREAM_TREADY;
    sc_out< sc_logic > OUT_STREAM_TVALID;
    sc_in< sc_logic > OUT_STREAM_TREADY;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;


    // Module declarations
    toGray(sc_module_name name);
    SC_HAS_PROCESS(toGray);

    ~toGray();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    toGray_Block_proc* toGray_Block_proc_U0;
    toGray_AXIvideo2Mat* toGray_AXIvideo2Mat_U0;
    toGray_CvtColor* toGray_CvtColor_U0;
    toGray_Equalize* toGray_Equalize_U0;
    toGray_Mat2AXIvideo_8_1080_1920_0_s* toGray_Mat2AXIvideo_8_1080_1920_0_U0;
    FIFO_toGray_inMat_rows_V_channel* inMat_rows_V_channel_U;
    FIFO_toGray_inMat_rows_V_channel1* inMat_rows_V_channel1_U;
    FIFO_toGray_inMat_cols_V_channel* inMat_cols_V_channel_U;
    FIFO_toGray_inMat_cols_V_channel1* inMat_cols_V_channel1_U;
    FIFO_toGray_grayMat_rows_V* grayMat_rows_V_U;
    FIFO_toGray_grayMat_cols_V* grayMat_cols_V_U;
    FIFO_toGray_outMat_rows_V* outMat_rows_V_U;
    FIFO_toGray_outMat_cols_V* outMat_cols_V_U;
    FIFO_toGray_inMat_data_stream_0_V* inMat_data_stream_0_V_U;
    FIFO_toGray_inMat_data_stream_1_V* inMat_data_stream_1_V_U;
    FIFO_toGray_inMat_data_stream_2_V* inMat_data_stream_2_V_U;
    FIFO_toGray_grayMat_data_stream_0_V* grayMat_data_stream_0_V_U;
    FIFO_toGray_outMat_data_stream_0_V* outMat_data_stream_0_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > toGray_Block_proc_U0_ap_start;
    sc_signal< sc_logic > toGray_Block_proc_U0_ap_done;
    sc_signal< sc_logic > toGray_Block_proc_U0_ap_continue;
    sc_signal< sc_logic > toGray_Block_proc_U0_ap_idle;
    sc_signal< sc_logic > toGray_Block_proc_U0_ap_ready;
    sc_signal< sc_lv<32> > toGray_Block_proc_U0_rows;
    sc_signal< sc_lv<32> > toGray_Block_proc_U0_cols;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_0;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_1;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_2;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_3;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_4;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_5;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_6;
    sc_signal< sc_lv<12> > toGray_Block_proc_U0_ap_return_7;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_inMat_cols_V_channel;
    sc_signal< sc_logic > inMat_cols_V_channel_full_n;
    sc_signal< sc_logic > ap_reg_ready_inMat_cols_V_channel_full_n;
    sc_signal< sc_logic > ap_sig_ready_inMat_cols_V_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_inMat_rows_V_channel1;
    sc_signal< sc_logic > inMat_rows_V_channel1_full_n;
    sc_signal< sc_logic > ap_reg_ready_inMat_rows_V_channel1_full_n;
    sc_signal< sc_logic > ap_sig_ready_inMat_rows_V_channel1_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_inMat_rows_V_channel;
    sc_signal< sc_logic > inMat_rows_V_channel_full_n;
    sc_signal< sc_logic > ap_reg_ready_inMat_rows_V_channel_full_n;
    sc_signal< sc_logic > ap_sig_ready_inMat_rows_V_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_inMat_cols_V_channel1;
    sc_signal< sc_logic > inMat_cols_V_channel1_full_n;
    sc_signal< sc_logic > ap_reg_ready_inMat_cols_V_channel1_full_n;
    sc_signal< sc_logic > ap_sig_ready_inMat_cols_V_channel1_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_grayMat_rows_V;
    sc_signal< sc_logic > grayMat_rows_V_full_n;
    sc_signal< sc_logic > ap_reg_ready_grayMat_rows_V_full_n;
    sc_signal< sc_logic > ap_sig_ready_grayMat_rows_V_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_grayMat_cols_V;
    sc_signal< sc_logic > grayMat_cols_V_full_n;
    sc_signal< sc_logic > ap_reg_ready_grayMat_cols_V_full_n;
    sc_signal< sc_logic > ap_sig_ready_grayMat_cols_V_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_outMat_rows_V;
    sc_signal< sc_logic > outMat_rows_V_full_n;
    sc_signal< sc_logic > ap_reg_ready_outMat_rows_V_full_n;
    sc_signal< sc_logic > ap_sig_ready_outMat_rows_V_full_n;
    sc_signal< sc_logic > ap_chn_write_toGray_Block_proc_U0_outMat_cols_V;
    sc_signal< sc_logic > outMat_cols_V_full_n;
    sc_signal< sc_logic > ap_reg_ready_outMat_cols_V_full_n;
    sc_signal< sc_logic > ap_sig_ready_outMat_cols_V_full_n;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_ap_start;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_ap_done;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_ap_continue;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_ap_idle;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_lv<24> > toGray_AXIvideo2Mat_U0_IN_STREAM_TDATA;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_IN_STREAM_TVALID;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_IN_STREAM_TREADY;
    sc_signal< sc_lv<3> > toGray_AXIvideo2Mat_U0_IN_STREAM_TKEEP;
    sc_signal< sc_lv<3> > toGray_AXIvideo2Mat_U0_IN_STREAM_TSTRB;
    sc_signal< sc_lv<1> > toGray_AXIvideo2Mat_U0_IN_STREAM_TUSER;
    sc_signal< sc_lv<1> > toGray_AXIvideo2Mat_U0_IN_STREAM_TLAST;
    sc_signal< sc_lv<1> > toGray_AXIvideo2Mat_U0_IN_STREAM_TID;
    sc_signal< sc_lv<1> > toGray_AXIvideo2Mat_U0_IN_STREAM_TDEST;
    sc_signal< sc_lv<12> > toGray_AXIvideo2Mat_U0_img_rows_V_read;
    sc_signal< sc_lv<12> > toGray_AXIvideo2Mat_U0_img_cols_V_read;
    sc_signal< sc_lv<8> > toGray_AXIvideo2Mat_U0_img_data_stream_0_V_din;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_img_data_stream_0_V_full_n;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_img_data_stream_0_V_write;
    sc_signal< sc_lv<8> > toGray_AXIvideo2Mat_U0_img_data_stream_1_V_din;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_img_data_stream_1_V_full_n;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_img_data_stream_1_V_write;
    sc_signal< sc_lv<8> > toGray_AXIvideo2Mat_U0_img_data_stream_2_V_din;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_img_data_stream_2_V_full_n;
    sc_signal< sc_logic > toGray_AXIvideo2Mat_U0_img_data_stream_2_V_write;
    sc_signal< sc_logic > toGray_CvtColor_U0_ap_start;
    sc_signal< sc_logic > toGray_CvtColor_U0_ap_done;
    sc_signal< sc_logic > toGray_CvtColor_U0_ap_continue;
    sc_signal< sc_logic > toGray_CvtColor_U0_ap_idle;
    sc_signal< sc_logic > toGray_CvtColor_U0_ap_ready;
    sc_signal< sc_lv<12> > toGray_CvtColor_U0_p_src_rows_V_read;
    sc_signal< sc_lv<12> > toGray_CvtColor_U0_p_src_cols_V_read;
    sc_signal< sc_lv<8> > toGray_CvtColor_U0_p_src_data_stream_0_V_dout;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_src_data_stream_0_V_empty_n;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_src_data_stream_0_V_read;
    sc_signal< sc_lv<8> > toGray_CvtColor_U0_p_src_data_stream_1_V_dout;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_src_data_stream_1_V_empty_n;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_src_data_stream_1_V_read;
    sc_signal< sc_lv<8> > toGray_CvtColor_U0_p_src_data_stream_2_V_dout;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_src_data_stream_2_V_empty_n;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > toGray_CvtColor_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_dst_data_stream_V_full_n;
    sc_signal< sc_logic > toGray_CvtColor_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > toGray_Equalize_U0_ap_start;
    sc_signal< sc_logic > toGray_Equalize_U0_ap_done;
    sc_signal< sc_logic > toGray_Equalize_U0_ap_continue;
    sc_signal< sc_logic > toGray_Equalize_U0_ap_idle;
    sc_signal< sc_logic > toGray_Equalize_U0_ap_ready;
    sc_signal< sc_lv<12> > toGray_Equalize_U0_p_src_rows_V_read;
    sc_signal< sc_lv<12> > toGray_Equalize_U0_p_src_cols_V_read;
    sc_signal< sc_lv<8> > toGray_Equalize_U0_p_src_data_stream_V_dout;
    sc_signal< sc_logic > toGray_Equalize_U0_p_src_data_stream_V_empty_n;
    sc_signal< sc_logic > toGray_Equalize_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<8> > toGray_Equalize_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > toGray_Equalize_U0_p_dst_data_stream_V_full_n;
    sc_signal< sc_logic > toGray_Equalize_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_start;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_done;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_ready;
    sc_signal< sc_lv<12> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_rows_V_read;
    sc_signal< sc_lv<12> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_cols_V_read;
    sc_signal< sc_lv<8> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read;
    sc_signal< sc_lv<8> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TDATA;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TVALID;
    sc_signal< sc_logic > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TREADY;
    sc_signal< sc_lv<1> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TKEEP;
    sc_signal< sc_lv<1> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TSTRB;
    sc_signal< sc_lv<1> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TUSER;
    sc_signal< sc_lv<1> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TLAST;
    sc_signal< sc_lv<1> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TID;
    sc_signal< sc_lv<1> > toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TDEST;
    sc_signal< sc_logic > ap_sig_hs_continue;
    sc_signal< sc_logic > inMat_rows_V_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > inMat_rows_V_channel_din;
    sc_signal< sc_logic > inMat_rows_V_channel_write;
    sc_signal< sc_lv<12> > inMat_rows_V_channel_dout;
    sc_signal< sc_logic > inMat_rows_V_channel_empty_n;
    sc_signal< sc_logic > inMat_rows_V_channel_read;
    sc_signal< sc_logic > inMat_rows_V_channel1_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > inMat_rows_V_channel1_din;
    sc_signal< sc_logic > inMat_rows_V_channel1_write;
    sc_signal< sc_lv<12> > inMat_rows_V_channel1_dout;
    sc_signal< sc_logic > inMat_rows_V_channel1_empty_n;
    sc_signal< sc_logic > inMat_rows_V_channel1_read;
    sc_signal< sc_logic > inMat_cols_V_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > inMat_cols_V_channel_din;
    sc_signal< sc_logic > inMat_cols_V_channel_write;
    sc_signal< sc_lv<12> > inMat_cols_V_channel_dout;
    sc_signal< sc_logic > inMat_cols_V_channel_empty_n;
    sc_signal< sc_logic > inMat_cols_V_channel_read;
    sc_signal< sc_logic > inMat_cols_V_channel1_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > inMat_cols_V_channel1_din;
    sc_signal< sc_logic > inMat_cols_V_channel1_write;
    sc_signal< sc_lv<12> > inMat_cols_V_channel1_dout;
    sc_signal< sc_logic > inMat_cols_V_channel1_empty_n;
    sc_signal< sc_logic > inMat_cols_V_channel1_read;
    sc_signal< sc_logic > grayMat_rows_V_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > grayMat_rows_V_din;
    sc_signal< sc_logic > grayMat_rows_V_write;
    sc_signal< sc_lv<12> > grayMat_rows_V_dout;
    sc_signal< sc_logic > grayMat_rows_V_empty_n;
    sc_signal< sc_logic > grayMat_rows_V_read;
    sc_signal< sc_logic > grayMat_cols_V_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > grayMat_cols_V_din;
    sc_signal< sc_logic > grayMat_cols_V_write;
    sc_signal< sc_lv<12> > grayMat_cols_V_dout;
    sc_signal< sc_logic > grayMat_cols_V_empty_n;
    sc_signal< sc_logic > grayMat_cols_V_read;
    sc_signal< sc_logic > outMat_rows_V_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > outMat_rows_V_din;
    sc_signal< sc_logic > outMat_rows_V_write;
    sc_signal< sc_lv<12> > outMat_rows_V_dout;
    sc_signal< sc_logic > outMat_rows_V_empty_n;
    sc_signal< sc_logic > outMat_rows_V_read;
    sc_signal< sc_logic > outMat_cols_V_U_ap_dummy_ce;
    sc_signal< sc_lv<12> > outMat_cols_V_din;
    sc_signal< sc_logic > outMat_cols_V_write;
    sc_signal< sc_lv<12> > outMat_cols_V_dout;
    sc_signal< sc_logic > outMat_cols_V_empty_n;
    sc_signal< sc_logic > outMat_cols_V_read;
    sc_signal< sc_logic > inMat_data_stream_0_V_U_ap_dummy_ce;
    sc_signal< sc_lv<8> > inMat_data_stream_0_V_din;
    sc_signal< sc_logic > inMat_data_stream_0_V_full_n;
    sc_signal< sc_logic > inMat_data_stream_0_V_write;
    sc_signal< sc_lv<8> > inMat_data_stream_0_V_dout;
    sc_signal< sc_logic > inMat_data_stream_0_V_empty_n;
    sc_signal< sc_logic > inMat_data_stream_0_V_read;
    sc_signal< sc_logic > inMat_data_stream_1_V_U_ap_dummy_ce;
    sc_signal< sc_lv<8> > inMat_data_stream_1_V_din;
    sc_signal< sc_logic > inMat_data_stream_1_V_full_n;
    sc_signal< sc_logic > inMat_data_stream_1_V_write;
    sc_signal< sc_lv<8> > inMat_data_stream_1_V_dout;
    sc_signal< sc_logic > inMat_data_stream_1_V_empty_n;
    sc_signal< sc_logic > inMat_data_stream_1_V_read;
    sc_signal< sc_logic > inMat_data_stream_2_V_U_ap_dummy_ce;
    sc_signal< sc_lv<8> > inMat_data_stream_2_V_din;
    sc_signal< sc_logic > inMat_data_stream_2_V_full_n;
    sc_signal< sc_logic > inMat_data_stream_2_V_write;
    sc_signal< sc_lv<8> > inMat_data_stream_2_V_dout;
    sc_signal< sc_logic > inMat_data_stream_2_V_empty_n;
    sc_signal< sc_logic > inMat_data_stream_2_V_read;
    sc_signal< sc_logic > grayMat_data_stream_0_V_U_ap_dummy_ce;
    sc_signal< sc_lv<8> > grayMat_data_stream_0_V_din;
    sc_signal< sc_logic > grayMat_data_stream_0_V_full_n;
    sc_signal< sc_logic > grayMat_data_stream_0_V_write;
    sc_signal< sc_lv<8> > grayMat_data_stream_0_V_dout;
    sc_signal< sc_logic > grayMat_data_stream_0_V_empty_n;
    sc_signal< sc_logic > grayMat_data_stream_0_V_read;
    sc_signal< sc_logic > outMat_data_stream_0_V_U_ap_dummy_ce;
    sc_signal< sc_lv<8> > outMat_data_stream_0_V_din;
    sc_signal< sc_logic > outMat_data_stream_0_V_full_n;
    sc_signal< sc_logic > outMat_data_stream_0_V_write;
    sc_signal< sc_lv<8> > outMat_data_stream_0_V_dout;
    sc_signal< sc_logic > outMat_data_stream_0_V_empty_n;
    sc_signal< sc_logic > outMat_data_stream_0_V_read;
    sc_signal< sc_logic > ap_reg_procdone_toGray_Block_proc_U0;
    sc_signal< sc_logic > ap_sig_hs_done;
    sc_signal< sc_logic > ap_reg_procdone_toGray_AXIvideo2Mat_U0;
    sc_signal< sc_logic > ap_reg_procdone_toGray_CvtColor_U0;
    sc_signal< sc_logic > ap_reg_procdone_toGray_Equalize_U0;
    sc_signal< sc_logic > ap_reg_procdone_toGray_Mat2AXIvideo_8_1080_1920_0_U0;
    sc_signal< sc_logic > ap_CS;
    sc_signal< sc_logic > ap_sig_top_allready;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const bool ap_true;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_IN_STREAM_TREADY();
    void thread_OUT_STREAM_TDATA();
    void thread_OUT_STREAM_TDEST();
    void thread_OUT_STREAM_TID();
    void thread_OUT_STREAM_TKEEP();
    void thread_OUT_STREAM_TLAST();
    void thread_OUT_STREAM_TSTRB();
    void thread_OUT_STREAM_TUSER();
    void thread_OUT_STREAM_TVALID();
    void thread_ap_chn_write_toGray_Block_proc_U0_grayMat_cols_V();
    void thread_ap_chn_write_toGray_Block_proc_U0_grayMat_rows_V();
    void thread_ap_chn_write_toGray_Block_proc_U0_inMat_cols_V_channel();
    void thread_ap_chn_write_toGray_Block_proc_U0_inMat_cols_V_channel1();
    void thread_ap_chn_write_toGray_Block_proc_U0_inMat_rows_V_channel();
    void thread_ap_chn_write_toGray_Block_proc_U0_inMat_rows_V_channel1();
    void thread_ap_chn_write_toGray_Block_proc_U0_outMat_cols_V();
    void thread_ap_chn_write_toGray_Block_proc_U0_outMat_rows_V();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_hs_continue();
    void thread_ap_sig_hs_done();
    void thread_ap_sig_ready_grayMat_cols_V_full_n();
    void thread_ap_sig_ready_grayMat_rows_V_full_n();
    void thread_ap_sig_ready_inMat_cols_V_channel1_full_n();
    void thread_ap_sig_ready_inMat_cols_V_channel_full_n();
    void thread_ap_sig_ready_inMat_rows_V_channel1_full_n();
    void thread_ap_sig_ready_inMat_rows_V_channel_full_n();
    void thread_ap_sig_ready_outMat_cols_V_full_n();
    void thread_ap_sig_ready_outMat_rows_V_full_n();
    void thread_ap_sig_top_allready();
    void thread_grayMat_cols_V_U_ap_dummy_ce();
    void thread_grayMat_cols_V_din();
    void thread_grayMat_cols_V_read();
    void thread_grayMat_cols_V_write();
    void thread_grayMat_data_stream_0_V_U_ap_dummy_ce();
    void thread_grayMat_data_stream_0_V_din();
    void thread_grayMat_data_stream_0_V_read();
    void thread_grayMat_data_stream_0_V_write();
    void thread_grayMat_rows_V_U_ap_dummy_ce();
    void thread_grayMat_rows_V_din();
    void thread_grayMat_rows_V_read();
    void thread_grayMat_rows_V_write();
    void thread_inMat_cols_V_channel1_U_ap_dummy_ce();
    void thread_inMat_cols_V_channel1_din();
    void thread_inMat_cols_V_channel1_read();
    void thread_inMat_cols_V_channel1_write();
    void thread_inMat_cols_V_channel_U_ap_dummy_ce();
    void thread_inMat_cols_V_channel_din();
    void thread_inMat_cols_V_channel_read();
    void thread_inMat_cols_V_channel_write();
    void thread_inMat_data_stream_0_V_U_ap_dummy_ce();
    void thread_inMat_data_stream_0_V_din();
    void thread_inMat_data_stream_0_V_read();
    void thread_inMat_data_stream_0_V_write();
    void thread_inMat_data_stream_1_V_U_ap_dummy_ce();
    void thread_inMat_data_stream_1_V_din();
    void thread_inMat_data_stream_1_V_read();
    void thread_inMat_data_stream_1_V_write();
    void thread_inMat_data_stream_2_V_U_ap_dummy_ce();
    void thread_inMat_data_stream_2_V_din();
    void thread_inMat_data_stream_2_V_read();
    void thread_inMat_data_stream_2_V_write();
    void thread_inMat_rows_V_channel1_U_ap_dummy_ce();
    void thread_inMat_rows_V_channel1_din();
    void thread_inMat_rows_V_channel1_read();
    void thread_inMat_rows_V_channel1_write();
    void thread_inMat_rows_V_channel_U_ap_dummy_ce();
    void thread_inMat_rows_V_channel_din();
    void thread_inMat_rows_V_channel_read();
    void thread_inMat_rows_V_channel_write();
    void thread_outMat_cols_V_U_ap_dummy_ce();
    void thread_outMat_cols_V_din();
    void thread_outMat_cols_V_read();
    void thread_outMat_cols_V_write();
    void thread_outMat_data_stream_0_V_U_ap_dummy_ce();
    void thread_outMat_data_stream_0_V_din();
    void thread_outMat_data_stream_0_V_read();
    void thread_outMat_data_stream_0_V_write();
    void thread_outMat_rows_V_U_ap_dummy_ce();
    void thread_outMat_rows_V_din();
    void thread_outMat_rows_V_read();
    void thread_outMat_rows_V_write();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TDATA();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TDEST();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TID();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TKEEP();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TLAST();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TSTRB();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TUSER();
    void thread_toGray_AXIvideo2Mat_U0_IN_STREAM_TVALID();
    void thread_toGray_AXIvideo2Mat_U0_ap_continue();
    void thread_toGray_AXIvideo2Mat_U0_ap_start();
    void thread_toGray_AXIvideo2Mat_U0_img_cols_V_read();
    void thread_toGray_AXIvideo2Mat_U0_img_data_stream_0_V_full_n();
    void thread_toGray_AXIvideo2Mat_U0_img_data_stream_1_V_full_n();
    void thread_toGray_AXIvideo2Mat_U0_img_data_stream_2_V_full_n();
    void thread_toGray_AXIvideo2Mat_U0_img_rows_V_read();
    void thread_toGray_Block_proc_U0_ap_continue();
    void thread_toGray_Block_proc_U0_ap_start();
    void thread_toGray_Block_proc_U0_cols();
    void thread_toGray_Block_proc_U0_rows();
    void thread_toGray_CvtColor_U0_ap_continue();
    void thread_toGray_CvtColor_U0_ap_start();
    void thread_toGray_CvtColor_U0_p_dst_data_stream_V_full_n();
    void thread_toGray_CvtColor_U0_p_src_cols_V_read();
    void thread_toGray_CvtColor_U0_p_src_data_stream_0_V_dout();
    void thread_toGray_CvtColor_U0_p_src_data_stream_0_V_empty_n();
    void thread_toGray_CvtColor_U0_p_src_data_stream_1_V_dout();
    void thread_toGray_CvtColor_U0_p_src_data_stream_1_V_empty_n();
    void thread_toGray_CvtColor_U0_p_src_data_stream_2_V_dout();
    void thread_toGray_CvtColor_U0_p_src_data_stream_2_V_empty_n();
    void thread_toGray_CvtColor_U0_p_src_rows_V_read();
    void thread_toGray_Equalize_U0_ap_continue();
    void thread_toGray_Equalize_U0_ap_start();
    void thread_toGray_Equalize_U0_p_dst_data_stream_V_full_n();
    void thread_toGray_Equalize_U0_p_src_cols_V_read();
    void thread_toGray_Equalize_U0_p_src_data_stream_V_dout();
    void thread_toGray_Equalize_U0_p_src_data_stream_V_empty_n();
    void thread_toGray_Equalize_U0_p_src_rows_V_read();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_OUT_STREAM_TREADY();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_ap_start();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_cols_V_read();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n();
    void thread_toGray_Mat2AXIvideo_8_1080_1920_0_U0_img_rows_V_read();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
