// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "toGray_CvtColor.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic toGray_CvtColor::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic toGray_CvtColor::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> toGray_CvtColor::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> toGray_CvtColor::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> toGray_CvtColor::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> toGray_CvtColor::ap_ST_st8_fsm_3 = "1000";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> toGray_CvtColor::ap_const_lv1_1 = "1";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_1 = "1";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_2 = "10";
const sc_lv<1> toGray_CvtColor::ap_const_lv1_0 = "0";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_3 = "11";
const sc_lv<11> toGray_CvtColor::ap_const_lv11_0 = "00000000000";
const sc_lv<11> toGray_CvtColor::ap_const_lv11_1 = "1";
const sc_lv<31> toGray_CvtColor::ap_const_lv31_4C8B43 = "10011001000101101000011";
const sc_lv<30> toGray_CvtColor::ap_const_lv30_1D2F1A = "111010010111100011010";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_9645A1 = "100101100100010110100001";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_18 = "11000";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_1F = "11111";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_17 = "10111";
const sc_lv<32> toGray_CvtColor::ap_const_lv32_7 = "111";
const sc_lv<8> toGray_CvtColor::ap_const_lv8_FF = "11111111";

toGray_CvtColor::toGray_CvtColor(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_fu_160_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_fu_160_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_104);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond_reg_313_pp0_it3 );

    SC_METHOD(thread_ap_sig_bdd_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_55);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_67);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_78);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_92);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( exitcond_reg_313 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_78 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_67 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_3);
    sensitive << ( ap_sig_bdd_153 );

    SC_METHOD(thread_exitcond2_fu_160_p2);
    sensitive << ( p_src_rows_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_cast_fu_156_p1 );

    SC_METHOD(thread_exitcond_fu_175_p2);
    sensitive << ( p_src_cols_V_read );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( j_cast_fu_171_p1 );

    SC_METHOD(thread_i_1_fu_165_p2);
    sensitive << ( i_reg_133 );

    SC_METHOD(thread_i_cast_fu_156_p1);
    sensitive << ( i_reg_133 );

    SC_METHOD(thread_j_1_fu_180_p2);
    sensitive << ( j_reg_144 );

    SC_METHOD(thread_j_cast_fu_171_p1);
    sensitive << ( j_reg_144 );

    SC_METHOD(thread_not_carry_fu_279_p2);
    sensitive << ( tmp_11_fu_266_p3 );
    sensitive << ( p_Result_1_i_i_i_not_fu_274_p2 );

    SC_METHOD(thread_p_Result_1_i_i_i_not_fu_274_p2);
    sensitive << ( tmp_10_reg_352 );

    SC_METHOD(thread_p_Val2_1_fu_209_p2);
    sensitive << ( r_V_4_i_reg_332 );
    sensitive << ( tmp1_i_cast_fu_205_p1 );

    SC_METHOD(thread_p_Val2_4_fu_261_p2);
    sensitive << ( p_Val2_3_reg_342 );
    sensitive << ( tmp_38_i_i_i_fu_258_p1 );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_313_pp0_it3 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( p_Val2_4_fu_261_p2 );
    sensitive << ( not_carry_fu_279_p2 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_313_pp0_it3 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_p_src_data_stream_0_V_read);
    sensitive << ( exitcond_reg_313 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_p_src_data_stream_1_V_read);
    sensitive << ( exitcond_reg_313 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_p_src_data_stream_2_V_read);
    sensitive << ( exitcond_reg_313 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_r_V_1_fu_227_p2);
    sensitive << ( tmp_i_cast_reg_337 );
    sensitive << ( r_V_3_i_fu_221_p2 );

    SC_METHOD(thread_r_V_3_i_fu_221_p0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( r_V_3_i_fu_221_p00 );

    SC_METHOD(thread_r_V_3_i_fu_221_p00);
    sensitive << ( ap_reg_ppstg_tmp_14_reg_327_pp0_it2 );

    SC_METHOD(thread_r_V_3_i_fu_221_p2);
    sensitive << ( r_V_3_i_fu_221_p0 );

    SC_METHOD(thread_r_V_4_i_fu_190_p0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( r_V_4_i_fu_190_p00 );

    SC_METHOD(thread_r_V_4_i_fu_190_p00);
    sensitive << ( p_src_data_stream_2_V_dout );

    SC_METHOD(thread_r_V_4_i_fu_190_p2);
    sensitive << ( r_V_4_i_fu_190_p0 );

    SC_METHOD(thread_r_V_fu_199_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( r_V_fu_199_p00 );

    SC_METHOD(thread_r_V_fu_199_p00);
    sensitive << ( tmp_13_reg_322 );

    SC_METHOD(thread_r_V_fu_199_p2);
    sensitive << ( r_V_fu_199_p0 );

    SC_METHOD(thread_tmp1_i_cast_fu_205_p1);
    sensitive << ( r_V_fu_199_p2 );

    SC_METHOD(thread_tmp_11_fu_266_p3);
    sensitive << ( p_Val2_4_fu_261_p2 );

    SC_METHOD(thread_tmp_38_i_i_i_fu_258_p1);
    sensitive << ( tmp_reg_347 );

    SC_METHOD(thread_tmp_i_cast_fu_214_p1);
    sensitive << ( p_Val2_1_fu_209_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_55 );
    sensitive << ( exitcond2_fu_160_p2 );
    sensitive << ( exitcond_fu_175_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_92 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_bdd_104 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "toGray_CvtColor_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_rows_V_read, "(port)p_src_rows_V_read");
    sc_trace(mVcdFile, p_src_cols_V_read, "(port)p_src_cols_V_read");
    sc_trace(mVcdFile, p_src_data_stream_0_V_dout, "(port)p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_0_V_empty_n, "(port)p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_read, "(port)p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, p_src_data_stream_1_V_dout, "(port)p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_1_V_empty_n, "(port)p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_1_V_read, "(port)p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, p_src_data_stream_2_V_dout, "(port)p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_2_V_empty_n, "(port)p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_read, "(port)p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, j_reg_144, "j_reg_144");
    sc_trace(mVcdFile, ap_sig_bdd_55, "ap_sig_bdd_55");
    sc_trace(mVcdFile, exitcond2_fu_160_p2, "exitcond2_fu_160_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_67, "ap_sig_bdd_67");
    sc_trace(mVcdFile, i_1_fu_165_p2, "i_1_fu_165_p2");
    sc_trace(mVcdFile, i_1_reg_308, "i_1_reg_308");
    sc_trace(mVcdFile, exitcond_fu_175_p2, "exitcond_fu_175_p2");
    sc_trace(mVcdFile, exitcond_reg_313, "exitcond_reg_313");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_78, "ap_sig_bdd_78");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_92, "ap_sig_bdd_92");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_313_pp0_it3, "ap_reg_ppstg_exitcond_reg_313_pp0_it3");
    sc_trace(mVcdFile, ap_sig_bdd_104, "ap_sig_bdd_104");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_313_pp0_it1, "ap_reg_ppstg_exitcond_reg_313_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_313_pp0_it2, "ap_reg_ppstg_exitcond_reg_313_pp0_it2");
    sc_trace(mVcdFile, j_1_fu_180_p2, "j_1_fu_180_p2");
    sc_trace(mVcdFile, tmp_13_reg_322, "tmp_13_reg_322");
    sc_trace(mVcdFile, tmp_14_reg_327, "tmp_14_reg_327");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_14_reg_327_pp0_it2, "ap_reg_ppstg_tmp_14_reg_327_pp0_it2");
    sc_trace(mVcdFile, r_V_4_i_fu_190_p2, "r_V_4_i_fu_190_p2");
    sc_trace(mVcdFile, r_V_4_i_reg_332, "r_V_4_i_reg_332");
    sc_trace(mVcdFile, tmp_i_cast_fu_214_p1, "tmp_i_cast_fu_214_p1");
    sc_trace(mVcdFile, tmp_i_cast_reg_337, "tmp_i_cast_reg_337");
    sc_trace(mVcdFile, p_Val2_3_reg_342, "p_Val2_3_reg_342");
    sc_trace(mVcdFile, tmp_reg_347, "tmp_reg_347");
    sc_trace(mVcdFile, tmp_10_reg_352, "tmp_10_reg_352");
    sc_trace(mVcdFile, i_reg_133, "i_reg_133");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_3, "ap_sig_cseq_ST_st8_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_153, "ap_sig_bdd_153");
    sc_trace(mVcdFile, i_cast_fu_156_p1, "i_cast_fu_156_p1");
    sc_trace(mVcdFile, j_cast_fu_171_p1, "j_cast_fu_171_p1");
    sc_trace(mVcdFile, r_V_4_i_fu_190_p0, "r_V_4_i_fu_190_p0");
    sc_trace(mVcdFile, r_V_fu_199_p0, "r_V_fu_199_p0");
    sc_trace(mVcdFile, r_V_fu_199_p2, "r_V_fu_199_p2");
    sc_trace(mVcdFile, tmp1_i_cast_fu_205_p1, "tmp1_i_cast_fu_205_p1");
    sc_trace(mVcdFile, p_Val2_1_fu_209_p2, "p_Val2_1_fu_209_p2");
    sc_trace(mVcdFile, r_V_3_i_fu_221_p0, "r_V_3_i_fu_221_p0");
    sc_trace(mVcdFile, r_V_3_i_fu_221_p2, "r_V_3_i_fu_221_p2");
    sc_trace(mVcdFile, r_V_1_fu_227_p2, "r_V_1_fu_227_p2");
    sc_trace(mVcdFile, tmp_38_i_i_i_fu_258_p1, "tmp_38_i_i_i_fu_258_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_261_p2, "p_Val2_4_fu_261_p2");
    sc_trace(mVcdFile, tmp_11_fu_266_p3, "tmp_11_fu_266_p3");
    sc_trace(mVcdFile, p_Result_1_i_i_i_not_fu_274_p2, "p_Result_1_i_i_i_not_fu_274_p2");
    sc_trace(mVcdFile, not_carry_fu_279_p2, "not_carry_fu_279_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, r_V_3_i_fu_221_p00, "r_V_3_i_fu_221_p00");
    sc_trace(mVcdFile, r_V_4_i_fu_190_p00, "r_V_4_i_fu_190_p00");
    sc_trace(mVcdFile, r_V_fu_199_p00, "r_V_fu_199_p00");
#endif

    }
}

toGray_CvtColor::~toGray_CvtColor() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void toGray_CvtColor::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
             !esl_seteq<1,1,1>(exitcond_fu_175_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
             esl_seteq<1,1,1>(exitcond_fu_175_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
                     !esl_seteq<1,1,1>(exitcond_fu_175_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_55.read())) {
        i_reg_133 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_3.read())) {
        i_reg_133 = i_1_reg_308.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
         esl_seteq<1,1,1>(exitcond_fu_175_p2.read(), ap_const_lv1_0))) {
        j_reg_144 = j_1_fu_180_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0))) {
        j_reg_144 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        ap_reg_ppstg_exitcond_reg_313_pp0_it1 = exitcond_reg_313.read();
        exitcond_reg_313 = exitcond_fu_175_p2.read();
    }
    if (!((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
        ap_reg_ppstg_exitcond_reg_313_pp0_it2 = ap_reg_ppstg_exitcond_reg_313_pp0_it1.read();
        ap_reg_ppstg_exitcond_reg_313_pp0_it3 = ap_reg_ppstg_exitcond_reg_313_pp0_it2.read();
        ap_reg_ppstg_tmp_14_reg_327_pp0_it2 = tmp_14_reg_327.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_1_reg_308 = i_1_fu_165_p2.read();
    }
    if ((!((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_313_pp0_it2.read()))) {
        p_Val2_3_reg_342 = r_V_1_fu_227_p2.read().range(31, 24);
        tmp_10_reg_352 = r_V_1_fu_227_p2.read().range(31, 31);
        tmp_reg_347 = r_V_1_fu_227_p2.read().range(23, 23);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0) && !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        r_V_4_i_reg_332 = r_V_4_i_fu_190_p2.read();
        tmp_13_reg_322 = p_src_data_stream_0_V_dout.read();
        tmp_14_reg_327 = p_src_data_stream_1_V_dout.read();
    }
    if ((!((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_313_pp0_it1.read()))) {
        tmp_i_cast_reg_337 = tmp_i_cast_fu_214_p1.read();
    }
}

void toGray_CvtColor::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_ap_sig_bdd_104() {
    ap_sig_bdd_104 = (esl_seteq<1,1,1>(p_dst_data_stream_V_full_n.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_313_pp0_it3.read()));
}

void toGray_CvtColor::thread_ap_sig_bdd_153() {
    ap_sig_bdd_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void toGray_CvtColor::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void toGray_CvtColor::thread_ap_sig_bdd_55() {
    ap_sig_bdd_55 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void toGray_CvtColor::thread_ap_sig_bdd_67() {
    ap_sig_bdd_67 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void toGray_CvtColor::thread_ap_sig_bdd_78() {
    ap_sig_bdd_78 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void toGray_CvtColor::thread_ap_sig_bdd_92() {
    ap_sig_bdd_92 = ((esl_seteq<1,1,1>(p_src_data_stream_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_1_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_2_V_empty_n.read(), ap_const_logic_0)));
}

void toGray_CvtColor::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_78.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_67.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_ap_sig_cseq_ST_st8_fsm_3() {
    if (ap_sig_bdd_153.read()) {
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_exitcond2_fu_160_p2() {
    exitcond2_fu_160_p2 = (!i_cast_fu_156_p1.read().is_01() || !p_src_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(i_cast_fu_156_p1.read() == p_src_rows_V_read.read());
}

void toGray_CvtColor::thread_exitcond_fu_175_p2() {
    exitcond_fu_175_p2 = (!j_cast_fu_171_p1.read().is_01() || !p_src_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(j_cast_fu_171_p1.read() == p_src_cols_V_read.read());
}

void toGray_CvtColor::thread_i_1_fu_165_p2() {
    i_1_fu_165_p2 = (!i_reg_133.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_reg_133.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void toGray_CvtColor::thread_i_cast_fu_156_p1() {
    i_cast_fu_156_p1 = esl_zext<12,11>(i_reg_133.read());
}

void toGray_CvtColor::thread_j_1_fu_180_p2() {
    j_1_fu_180_p2 = (!j_reg_144.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(j_reg_144.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void toGray_CvtColor::thread_j_cast_fu_171_p1() {
    j_cast_fu_171_p1 = esl_zext<12,11>(j_reg_144.read());
}

void toGray_CvtColor::thread_not_carry_fu_279_p2() {
    not_carry_fu_279_p2 = (tmp_11_fu_266_p3.read() | p_Result_1_i_i_i_not_fu_274_p2.read());
}

void toGray_CvtColor::thread_p_Result_1_i_i_i_not_fu_274_p2() {
    p_Result_1_i_i_i_not_fu_274_p2 = (tmp_10_reg_352.read() ^ ap_const_lv1_1);
}

void toGray_CvtColor::thread_p_Val2_1_fu_209_p2() {
    p_Val2_1_fu_209_p2 = (!r_V_4_i_reg_332.read().is_01() || !tmp1_i_cast_fu_205_p1.read().is_01())? sc_lv<31>(): (sc_biguint<31>(r_V_4_i_reg_332.read()) + sc_biguint<31>(tmp1_i_cast_fu_205_p1.read()));
}

void toGray_CvtColor::thread_p_Val2_4_fu_261_p2() {
    p_Val2_4_fu_261_p2 = (!p_Val2_3_reg_342.read().is_01() || !tmp_38_i_i_i_fu_258_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_3_reg_342.read()) + sc_biguint<8>(tmp_38_i_i_i_fu_258_p1.read()));
}

void toGray_CvtColor::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = (!not_carry_fu_279_p2.read()[0].is_01())? sc_lv<8>(): ((not_carry_fu_279_p2.read()[0].to_bool())? p_Val2_4_fu_261_p2.read(): ap_const_lv8_FF);
}

void toGray_CvtColor::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_313_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_p_src_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        p_src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_p_src_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        p_src_data_stream_1_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_p_src_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_313.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        p_src_data_stream_2_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_2_V_read = ap_const_logic_0;
    }
}

void toGray_CvtColor::thread_r_V_1_fu_227_p2() {
    r_V_1_fu_227_p2 = (!r_V_3_i_fu_221_p2.read().is_01() || !tmp_i_cast_reg_337.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_3_i_fu_221_p2.read()) + sc_biguint<32>(tmp_i_cast_reg_337.read()));
}

void toGray_CvtColor::thread_r_V_3_i_fu_221_p0() {
    r_V_3_i_fu_221_p0 =  (sc_lv<8>) (r_V_3_i_fu_221_p00.read());
}

void toGray_CvtColor::thread_r_V_3_i_fu_221_p00() {
    r_V_3_i_fu_221_p00 = esl_zext<32,8>(ap_reg_ppstg_tmp_14_reg_327_pp0_it2.read());
}

void toGray_CvtColor::thread_r_V_3_i_fu_221_p2() {
    r_V_3_i_fu_221_p2 = (!r_V_3_i_fu_221_p0.read().is_01() || !ap_const_lv32_9645A1.is_01())? sc_lv<32>(): sc_biguint<8>(r_V_3_i_fu_221_p0.read()) * sc_biguint<32>(ap_const_lv32_9645A1);
}

void toGray_CvtColor::thread_r_V_4_i_fu_190_p0() {
    r_V_4_i_fu_190_p0 =  (sc_lv<8>) (r_V_4_i_fu_190_p00.read());
}

void toGray_CvtColor::thread_r_V_4_i_fu_190_p00() {
    r_V_4_i_fu_190_p00 = esl_zext<31,8>(p_src_data_stream_2_V_dout.read());
}

void toGray_CvtColor::thread_r_V_4_i_fu_190_p2() {
    r_V_4_i_fu_190_p2 = (!r_V_4_i_fu_190_p0.read().is_01() || !ap_const_lv31_4C8B43.is_01())? sc_lv<31>(): sc_biguint<8>(r_V_4_i_fu_190_p0.read()) * sc_biguint<31>(ap_const_lv31_4C8B43);
}

void toGray_CvtColor::thread_r_V_fu_199_p0() {
    r_V_fu_199_p0 =  (sc_lv<8>) (r_V_fu_199_p00.read());
}

void toGray_CvtColor::thread_r_V_fu_199_p00() {
    r_V_fu_199_p00 = esl_zext<30,8>(tmp_13_reg_322.read());
}

void toGray_CvtColor::thread_r_V_fu_199_p2() {
    r_V_fu_199_p2 = (!r_V_fu_199_p0.read().is_01() || !ap_const_lv30_1D2F1A.is_01())? sc_lv<30>(): sc_biguint<8>(r_V_fu_199_p0.read()) * sc_biguint<30>(ap_const_lv30_1D2F1A);
}

void toGray_CvtColor::thread_tmp1_i_cast_fu_205_p1() {
    tmp1_i_cast_fu_205_p1 = esl_zext<31,30>(r_V_fu_199_p2.read());
}

void toGray_CvtColor::thread_tmp_11_fu_266_p3() {
    tmp_11_fu_266_p3 = p_Val2_4_fu_261_p2.read().range(7, 7);
}

void toGray_CvtColor::thread_tmp_38_i_i_i_fu_258_p1() {
    tmp_38_i_i_i_fu_258_p1 = esl_zext<8,1>(tmp_reg_347.read());
}

void toGray_CvtColor::thread_tmp_i_cast_fu_214_p1() {
    tmp_i_cast_fu_214_p1 = esl_zext<32,31>(p_Val2_1_fu_209_p2.read());
}

void toGray_CvtColor::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_55.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond2_fu_160_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(exitcond_fu_175_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((ap_sig_bdd_92.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_104.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
  !esl_seteq<1,1,1>(exitcond_fu_175_p2.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st8_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

