// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "toGray_AXIvideo2Mat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic toGray_AXIvideo2Mat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic toGray_AXIvideo2Mat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_st1_fsm_0 = "1";
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_st2_fsm_1 = "10";
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_st3_fsm_2 = "100";
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_st4_fsm_3 = "1000";
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_pp1_stg0_fsm_4 = "10000";
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_st7_fsm_5 = "100000";
const sc_lv<7> toGray_AXIvideo2Mat::ap_ST_st8_fsm_6 = "1000000";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> toGray_AXIvideo2Mat::ap_const_lv1_1 = "1";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_1 = "1";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_3 = "11";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_4 = "100";
const sc_lv<1> toGray_AXIvideo2Mat::ap_const_lv1_0 = "0";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_5 = "101";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_6 = "110";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_2 = "10";
const sc_lv<12> toGray_AXIvideo2Mat::ap_const_lv12_0 = "000000000000";
const sc_lv<12> toGray_AXIvideo2Mat::ap_const_lv12_1 = "1";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_8 = "1000";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_F = "1111";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_10 = "10000";
const sc_lv<32> toGray_AXIvideo2Mat::ap_const_lv32_17 = "10111";
const bool toGray_AXIvideo2Mat::ap_true = true;

toGray_AXIvideo2Mat::toGray_AXIvideo2Mat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_IN_STREAM_TREADY);
    sensitive << ( IN_STREAM_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond2_fu_330_p2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( brmerge_fu_344_p2 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_5 );
    sensitive << ( ap_sig_bdd_163 );
    sensitive << ( eol_3_reg_288 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond1_fu_319_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond1_fu_319_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_reg_phiprechg_axi_last_V_2_reg_229pp1_it0);

    SC_METHOD(thread_ap_reg_phiprechg_eol_2_reg_253pp1_it0);

    SC_METHOD(thread_ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0);

    SC_METHOD(thread_ap_sig_bdd_101);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_112);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_119);
    sensitive << ( exitcond2_fu_330_p2 );
    sensitive << ( brmerge_fu_344_p2 );

    SC_METHOD(thread_ap_sig_bdd_120);
    sensitive << ( IN_STREAM_TVALID );
    sensitive << ( exitcond2_fu_330_p2 );
    sensitive << ( brmerge_fu_344_p2 );

    SC_METHOD(thread_ap_sig_bdd_133);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( exitcond2_reg_431 );

    SC_METHOD(thread_ap_sig_bdd_144);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_ap_sig_bdd_158);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_163);
    sensitive << ( IN_STREAM_TVALID );
    sensitive << ( eol_3_reg_288 );

    SC_METHOD(thread_ap_sig_bdd_181);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_188);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_211);
    sensitive << ( exitcond2_fu_330_p2 );
    sensitive << ( brmerge_fu_344_p2 );

    SC_METHOD(thread_ap_sig_bdd_229);
    sensitive << ( exitcond2_fu_330_p2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );

    SC_METHOD(thread_ap_sig_bdd_26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_75);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_87);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg0_fsm_4);
    sensitive << ( ap_sig_bdd_112 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_26 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_87 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_188 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_101 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_5);
    sensitive << ( ap_sig_bdd_158 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_6);
    sensitive << ( ap_sig_bdd_181 );

    SC_METHOD(thread_axi_data_V_1_phi_fu_198_p4);
    sensitive << ( axi_data_V_1_reg_195 );
    sensitive << ( p_Val2_s_reg_241 );
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_axi_last_V_1_mux_fu_356_p2);
    sensitive << ( eol_1_phi_fu_187_p4 );
    sensitive << ( not_sof_2_fu_350_p2 );

    SC_METHOD(thread_brmerge_fu_344_p2);
    sensitive << ( eol_phi_fu_221_p4 );
    sensitive << ( sof_1_fu_98 );

    SC_METHOD(thread_eol_1_phi_fu_187_p4);
    sensitive << ( eol_1_reg_184 );
    sensitive << ( axi_last_V_2_reg_229 );
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_eol_phi_fu_221_p4);
    sensitive << ( eol_reg_217 );
    sensitive << ( eol_2_reg_253 );
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_exitcond1_fu_319_p2);
    sensitive << ( img_rows_V_read );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_s_reg_173 );

    SC_METHOD(thread_exitcond2_fu_330_p2);
    sensitive << ( img_cols_V_read );
    sensitive << ( p_1_reg_206 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_i_V_fu_324_p2);
    sensitive << ( p_s_reg_173 );

    SC_METHOD(thread_img_data_stream_0_V_din);
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_1_reg_444 );

    SC_METHOD(thread_img_data_stream_0_V_write);
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_img_data_stream_1_V_din);
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_2_reg_449 );

    SC_METHOD(thread_img_data_stream_1_V_write);
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_img_data_stream_2_V_din);
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_7_reg_454 );

    SC_METHOD(thread_img_data_stream_2_V_write);
    sensitive << ( exitcond2_reg_431 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );

    SC_METHOD(thread_j_V_fu_335_p2);
    sensitive << ( p_1_reg_206 );

    SC_METHOD(thread_not_sof_2_fu_350_p2);
    sensitive << ( sof_1_fu_98 );

    SC_METHOD(thread_p_Val2_s_phi_fu_245_p4);
    sensitive << ( IN_STREAM_TDATA );
    sensitive << ( brmerge_fu_344_p2 );
    sensitive << ( axi_data_V_1_phi_fu_198_p4 );
    sensitive << ( ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0 );
    sensitive << ( ap_sig_bdd_229 );

    SC_METHOD(thread_tmp_1_fu_363_p1);
    sensitive << ( p_Val2_s_phi_fu_245_p4 );

    SC_METHOD(thread_tmp_user_V_fu_310_p1);
    sensitive << ( IN_STREAM_TUSER );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( IN_STREAM_TVALID );
    sensitive << ( ap_sig_bdd_75 );
    sensitive << ( exitcond1_fu_319_p2 );
    sensitive << ( exitcond2_fu_330_p2 );
    sensitive << ( ap_sig_bdd_120 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_bdd_133 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( ap_sig_bdd_163 );
    sensitive << ( eol_3_reg_288 );
    sensitive << ( tmp_user_V_fu_310_p1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000001";
    ap_reg_ppiten_pp1_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "toGray_AXIvideo2Mat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, IN_STREAM_TDATA, "(port)IN_STREAM_TDATA");
    sc_trace(mVcdFile, IN_STREAM_TVALID, "(port)IN_STREAM_TVALID");
    sc_trace(mVcdFile, IN_STREAM_TREADY, "(port)IN_STREAM_TREADY");
    sc_trace(mVcdFile, IN_STREAM_TKEEP, "(port)IN_STREAM_TKEEP");
    sc_trace(mVcdFile, IN_STREAM_TSTRB, "(port)IN_STREAM_TSTRB");
    sc_trace(mVcdFile, IN_STREAM_TUSER, "(port)IN_STREAM_TUSER");
    sc_trace(mVcdFile, IN_STREAM_TLAST, "(port)IN_STREAM_TLAST");
    sc_trace(mVcdFile, IN_STREAM_TID, "(port)IN_STREAM_TID");
    sc_trace(mVcdFile, IN_STREAM_TDEST, "(port)IN_STREAM_TDEST");
    sc_trace(mVcdFile, img_rows_V_read, "(port)img_rows_V_read");
    sc_trace(mVcdFile, img_cols_V_read, "(port)img_cols_V_read");
    sc_trace(mVcdFile, img_data_stream_0_V_din, "(port)img_data_stream_0_V_din");
    sc_trace(mVcdFile, img_data_stream_0_V_full_n, "(port)img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_data_stream_0_V_write, "(port)img_data_stream_0_V_write");
    sc_trace(mVcdFile, img_data_stream_1_V_din, "(port)img_data_stream_1_V_din");
    sc_trace(mVcdFile, img_data_stream_1_V_full_n, "(port)img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_data_stream_1_V_write, "(port)img_data_stream_1_V_write");
    sc_trace(mVcdFile, img_data_stream_2_V_din, "(port)img_data_stream_2_V_din");
    sc_trace(mVcdFile, img_data_stream_2_V_full_n, "(port)img_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_data_stream_2_V_write, "(port)img_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_26, "ap_sig_bdd_26");
    sc_trace(mVcdFile, eol_1_reg_184, "eol_1_reg_184");
    sc_trace(mVcdFile, axi_data_V_1_reg_195, "axi_data_V_1_reg_195");
    sc_trace(mVcdFile, p_1_reg_206, "p_1_reg_206");
    sc_trace(mVcdFile, eol_reg_217, "eol_reg_217");
    sc_trace(mVcdFile, axi_last_V_2_reg_229, "axi_last_V_2_reg_229");
    sc_trace(mVcdFile, p_Val2_s_reg_241, "p_Val2_s_reg_241");
    sc_trace(mVcdFile, eol_2_reg_253, "eol_2_reg_253");
    sc_trace(mVcdFile, ap_sig_bdd_75, "ap_sig_bdd_75");
    sc_trace(mVcdFile, tmp_data_V_reg_402, "tmp_data_V_reg_402");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_87, "ap_sig_bdd_87");
    sc_trace(mVcdFile, tmp_last_V_reg_410, "tmp_last_V_reg_410");
    sc_trace(mVcdFile, exitcond1_fu_319_p2, "exitcond1_fu_319_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_101, "ap_sig_bdd_101");
    sc_trace(mVcdFile, i_V_fu_324_p2, "i_V_fu_324_p2");
    sc_trace(mVcdFile, i_V_reg_426, "i_V_reg_426");
    sc_trace(mVcdFile, exitcond2_fu_330_p2, "exitcond2_fu_330_p2");
    sc_trace(mVcdFile, exitcond2_reg_431, "exitcond2_reg_431");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg0_fsm_4, "ap_sig_cseq_ST_pp1_stg0_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_112, "ap_sig_bdd_112");
    sc_trace(mVcdFile, brmerge_fu_344_p2, "brmerge_fu_344_p2");
    sc_trace(mVcdFile, ap_sig_bdd_120, "ap_sig_bdd_120");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it0, "ap_reg_ppiten_pp1_it0");
    sc_trace(mVcdFile, ap_sig_bdd_133, "ap_sig_bdd_133");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it1, "ap_reg_ppiten_pp1_it1");
    sc_trace(mVcdFile, j_V_fu_335_p2, "j_V_fu_335_p2");
    sc_trace(mVcdFile, tmp_1_fu_363_p1, "tmp_1_fu_363_p1");
    sc_trace(mVcdFile, tmp_1_reg_444, "tmp_1_reg_444");
    sc_trace(mVcdFile, tmp_2_reg_449, "tmp_2_reg_449");
    sc_trace(mVcdFile, tmp_7_reg_454, "tmp_7_reg_454");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_5, "ap_sig_cseq_ST_st7_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_158, "ap_sig_bdd_158");
    sc_trace(mVcdFile, ap_sig_bdd_163, "ap_sig_bdd_163");
    sc_trace(mVcdFile, axi_last_V_3_reg_264, "axi_last_V_3_reg_264");
    sc_trace(mVcdFile, axi_last_V1_reg_153, "axi_last_V1_reg_153");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_6, "ap_sig_cseq_ST_st8_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_181, "ap_sig_bdd_181");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_188, "ap_sig_bdd_188");
    sc_trace(mVcdFile, axi_data_V_3_reg_276, "axi_data_V_3_reg_276");
    sc_trace(mVcdFile, axi_data_V1_reg_163, "axi_data_V1_reg_163");
    sc_trace(mVcdFile, p_s_reg_173, "p_s_reg_173");
    sc_trace(mVcdFile, eol_1_phi_fu_187_p4, "eol_1_phi_fu_187_p4");
    sc_trace(mVcdFile, axi_data_V_1_phi_fu_198_p4, "axi_data_V_1_phi_fu_198_p4");
    sc_trace(mVcdFile, eol_phi_fu_221_p4, "eol_phi_fu_221_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_axi_last_V_2_reg_229pp1_it0, "ap_reg_phiprechg_axi_last_V_2_reg_229pp1_it0");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0, "ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0");
    sc_trace(mVcdFile, p_Val2_s_phi_fu_245_p4, "p_Val2_s_phi_fu_245_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_eol_2_reg_253pp1_it0, "ap_reg_phiprechg_eol_2_reg_253pp1_it0");
    sc_trace(mVcdFile, axi_last_V_1_mux_fu_356_p2, "axi_last_V_1_mux_fu_356_p2");
    sc_trace(mVcdFile, eol_3_reg_288, "eol_3_reg_288");
    sc_trace(mVcdFile, sof_1_fu_98, "sof_1_fu_98");
    sc_trace(mVcdFile, not_sof_2_fu_350_p2, "not_sof_2_fu_350_p2");
    sc_trace(mVcdFile, tmp_user_V_fu_310_p1, "tmp_user_V_fu_310_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_119, "ap_sig_bdd_119");
    sc_trace(mVcdFile, ap_sig_bdd_211, "ap_sig_bdd_211");
    sc_trace(mVcdFile, ap_sig_bdd_144, "ap_sig_bdd_144");
    sc_trace(mVcdFile, ap_sig_bdd_229, "ap_sig_bdd_229");
#endif

    }
}

toGray_AXIvideo2Mat::~toGray_AXIvideo2Mat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void toGray_AXIvideo2Mat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    !esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && 
             !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && 
             !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                     esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
                     !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && 
                     !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_data_V1_reg_163 = tmp_data_V_reg_402.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_data_V1_reg_163 = axi_data_V_3_reg_276.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        axi_data_V_1_reg_195 = p_Val2_s_reg_241.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
        axi_data_V_1_reg_195 = axi_data_V1_reg_163.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && 
         !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0))) {
        axi_data_V_3_reg_276 = axi_data_V_1_phi_fu_198_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()) && 
                !ap_sig_bdd_163.read())) {
        axi_data_V_3_reg_276 = IN_STREAM_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_last_V1_reg_153 = tmp_last_V_reg_410.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_last_V1_reg_153 = axi_last_V_3_reg_264.read();
    }
    if (ap_sig_bdd_144.read()) {
        if (ap_sig_bdd_211.read()) {
            axi_last_V_2_reg_229 = eol_1_phi_fu_187_p4.read();
        } else if (ap_sig_bdd_119.read()) {
            axi_last_V_2_reg_229 = IN_STREAM_TLAST.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            axi_last_V_2_reg_229 = ap_reg_phiprechg_axi_last_V_2_reg_229pp1_it0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && 
         !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0))) {
        axi_last_V_3_reg_264 = eol_1_phi_fu_187_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()) && 
                !ap_sig_bdd_163.read())) {
        axi_last_V_3_reg_264 = IN_STREAM_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        eol_1_reg_184 = axi_last_V_2_reg_229.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
        eol_1_reg_184 = axi_last_V1_reg_153.read();
    }
    if (ap_sig_bdd_144.read()) {
        if (ap_sig_bdd_211.read()) {
            eol_2_reg_253 = axi_last_V_1_mux_fu_356_p2.read();
        } else if (ap_sig_bdd_119.read()) {
            eol_2_reg_253 = IN_STREAM_TLAST.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            eol_2_reg_253 = ap_reg_phiprechg_eol_2_reg_253pp1_it0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && 
         !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0))) {
        eol_3_reg_288 = eol_phi_fu_221_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()) && 
                !ap_sig_bdd_163.read())) {
        eol_3_reg_288 = IN_STREAM_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        eol_reg_217 = eol_2_reg_253.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
        eol_reg_217 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        p_1_reg_206 = j_V_fu_335_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
        p_1_reg_206 = ap_const_lv12_0;
    }
    if (ap_sig_bdd_144.read()) {
        if (ap_sig_bdd_211.read()) {
            p_Val2_s_reg_241 = axi_data_V_1_phi_fu_198_p4.read();
        } else if (ap_sig_bdd_119.read()) {
            p_Val2_s_reg_241 = IN_STREAM_TDATA.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            p_Val2_s_reg_241 = ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        p_s_reg_173 = ap_const_lv12_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        p_s_reg_173 = i_V_reg_426.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        sof_1_fu_98 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        sof_1_fu_98 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        exitcond2_reg_431 = exitcond2_fu_330_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_V_reg_426 = i_V_fu_324_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        tmp_1_reg_444 = tmp_1_fu_363_p1.read();
        tmp_2_reg_449 = p_Val2_s_phi_fu_245_p4.read().range(15, 8);
        tmp_7_reg_454 = p_Val2_s_phi_fu_245_p4.read().range(23, 16);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(IN_STREAM_TVALID.read(), ap_const_logic_0))) {
        tmp_data_V_reg_402 = IN_STREAM_TDATA.read();
        tmp_last_V_reg_410 = IN_STREAM_TLAST.read();
    }
}

void toGray_AXIvideo2Mat::thread_IN_STREAM_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(IN_STREAM_TVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()) && 
          !ap_sig_bdd_163.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_344_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read())))))) {
        IN_STREAM_TREADY = ap_const_logic_1;
    } else {
        IN_STREAM_TREADY = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_reg_phiprechg_axi_last_V_2_reg_229pp1_it0() {
    ap_reg_phiprechg_axi_last_V_2_reg_229pp1_it0 =  (sc_lv<1>) ("X");
}

void toGray_AXIvideo2Mat::thread_ap_reg_phiprechg_eol_2_reg_253pp1_it0() {
    ap_reg_phiprechg_eol_2_reg_253pp1_it0 =  (sc_lv<1>) ("X");
}

void toGray_AXIvideo2Mat::thread_ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0() {
    ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_101() {
    ap_sig_bdd_101 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_112() {
    ap_sig_bdd_112 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_119() {
    ap_sig_bdd_119 = (esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_344_p2.read()));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_120() {
    ap_sig_bdd_120 = (esl_seteq<1,1,1>(IN_STREAM_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_344_p2.read()));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_133() {
    ap_sig_bdd_133 = ((esl_seteq<1,1,1>(img_data_stream_0_V_full_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_data_stream_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_data_stream_2_V_full_n.read(), ap_const_logic_0)));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_144() {
    ap_sig_bdd_144 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_158() {
    ap_sig_bdd_158 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_163() {
    ap_sig_bdd_163 = (esl_seteq<1,1,1>(IN_STREAM_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_181() {
    ap_sig_bdd_181 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_188() {
    ap_sig_bdd_188 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_211() {
    ap_sig_bdd_211 = (esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_344_p2.read()));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_229() {
    ap_sig_bdd_229 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_26() {
    ap_sig_bdd_26 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_75() {
    ap_sig_bdd_75 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void toGray_AXIvideo2Mat::thread_ap_sig_bdd_87() {
    ap_sig_bdd_87 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_pp1_stg0_fsm_4() {
    if (ap_sig_bdd_112.read()) {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_26.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_87.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_188.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_101.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_st7_fsm_5() {
    if (ap_sig_bdd_158.read()) {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_ap_sig_cseq_ST_st8_fsm_6() {
    if (ap_sig_bdd_181.read()) {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_axi_data_V_1_phi_fu_198_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) {
        axi_data_V_1_phi_fu_198_p4 = p_Val2_s_reg_241.read();
    } else {
        axi_data_V_1_phi_fu_198_p4 = axi_data_V_1_reg_195.read();
    }
}

void toGray_AXIvideo2Mat::thread_axi_last_V_1_mux_fu_356_p2() {
    axi_last_V_1_mux_fu_356_p2 = (eol_1_phi_fu_187_p4.read() | not_sof_2_fu_350_p2.read());
}

void toGray_AXIvideo2Mat::thread_brmerge_fu_344_p2() {
    brmerge_fu_344_p2 = (sof_1_fu_98.read() | eol_phi_fu_221_p4.read());
}

void toGray_AXIvideo2Mat::thread_eol_1_phi_fu_187_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) {
        eol_1_phi_fu_187_p4 = axi_last_V_2_reg_229.read();
    } else {
        eol_1_phi_fu_187_p4 = eol_1_reg_184.read();
    }
}

void toGray_AXIvideo2Mat::thread_eol_phi_fu_221_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) {
        eol_phi_fu_221_p4 = eol_2_reg_253.read();
    } else {
        eol_phi_fu_221_p4 = eol_reg_217.read();
    }
}

void toGray_AXIvideo2Mat::thread_exitcond1_fu_319_p2() {
    exitcond1_fu_319_p2 = (!p_s_reg_173.read().is_01() || !img_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_173.read() == img_rows_V_read.read());
}

void toGray_AXIvideo2Mat::thread_exitcond2_fu_330_p2() {
    exitcond2_fu_330_p2 = (!p_1_reg_206.read().is_01() || !img_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_206.read() == img_cols_V_read.read());
}

void toGray_AXIvideo2Mat::thread_i_V_fu_324_p2() {
    i_V_fu_324_p2 = (!p_s_reg_173.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(p_s_reg_173.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void toGray_AXIvideo2Mat::thread_img_data_stream_0_V_din() {
    img_data_stream_0_V_din = tmp_1_reg_444.read();
}

void toGray_AXIvideo2Mat::thread_img_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        img_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_data_stream_0_V_write = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_img_data_stream_1_V_din() {
    img_data_stream_1_V_din = tmp_2_reg_449.read();
}

void toGray_AXIvideo2Mat::thread_img_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        img_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_data_stream_1_V_write = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_img_data_stream_2_V_din() {
    img_data_stream_2_V_din = tmp_7_reg_454.read();
}

void toGray_AXIvideo2Mat::thread_img_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_431.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))))) {
        img_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_data_stream_2_V_write = ap_const_logic_0;
    }
}

void toGray_AXIvideo2Mat::thread_j_V_fu_335_p2() {
    j_V_fu_335_p2 = (!p_1_reg_206.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(p_1_reg_206.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void toGray_AXIvideo2Mat::thread_not_sof_2_fu_350_p2() {
    not_sof_2_fu_350_p2 = (sof_1_fu_98.read() ^ ap_const_lv1_1);
}

void toGray_AXIvideo2Mat::thread_p_Val2_s_phi_fu_245_p4() {
    if (ap_sig_bdd_229.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_344_p2.read())) {
            p_Val2_s_phi_fu_245_p4 = axi_data_V_1_phi_fu_198_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_344_p2.read())) {
            p_Val2_s_phi_fu_245_p4 = IN_STREAM_TDATA.read();
        } else {
            p_Val2_s_phi_fu_245_p4 = ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0.read();
        }
    } else {
        p_Val2_s_phi_fu_245_p4 = ap_reg_phiprechg_p_Val2_s_reg_241pp1_it0.read();
    }
}

void toGray_AXIvideo2Mat::thread_tmp_1_fu_363_p1() {
    tmp_1_fu_363_p1 = p_Val2_s_phi_fu_245_p4.read().range(8-1, 0);
}

void toGray_AXIvideo2Mat::thread_tmp_user_V_fu_310_p1() {
    tmp_user_V_fu_310_p1 = IN_STREAM_TUSER.read();
}

void toGray_AXIvideo2Mat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_75.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!esl_seteq<1,1,1>(IN_STREAM_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_310_p1.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else if ((!esl_seteq<1,1,1>(IN_STREAM_TVALID.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_310_p1.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_319_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((ap_sig_bdd_120.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read())) || (ap_sig_bdd_133.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) && !esl_seteq<1,1,1>(exitcond2_fu_330_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()) && !ap_sig_bdd_163.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else if ((!ap_sig_bdd_163.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, eol_3_reg_288.read()))) {
                ap_NS_fsm = ap_ST_st8_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

