<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="10">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>toGray_Block_proc</name>
      <ret_bitwidth>96</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>rows</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>val</originalName>
              <rtlName/>
              <coreName>AXI4LiteS</coreName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>cols</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>val</originalName>
              <rtlName/>
              <coreName>AXI4LiteS</coreName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>13</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>5</id>
              <name>cols_read</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>val</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>20</item>
            <item>21</item>
          </oprand_edges>
          <opcode>read</opcode>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>6</id>
              <name>rows_read</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>val</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>22</item>
            <item>23</item>
          </oprand_edges>
          <opcode>read</opcode>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>7</id>
              <name>inMat_rows_V</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>3</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>inMat.rows.V</originalName>
              <rtlName>inMat_rows_V_fu_31_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>24</item>
          </oprand_edges>
          <opcode>trunc</opcode>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>inMat_cols_V</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>inMat.cols.V</originalName>
              <rtlName>inMat_cols_V_fu_35_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>25</item>
          </oprand_edges>
          <opcode>trunc</opcode>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>9</id>
              <name>mrv</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>27</item>
            <item>28</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>10</id>
              <name>mrv_1</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>29</item>
            <item>30</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>11</id>
              <name>mrv_2</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>31</item>
            <item>32</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>12</id>
              <name>mrv_3</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>34</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>13</id>
              <name>mrv_4</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>35</item>
            <item>36</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>14</id>
              <name>mrv_5</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>37</item>
            <item>38</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>15</id>
              <name>mrv_6</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>39</item>
            <item>40</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>16</id>
              <name>mrv_7</name>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>41</item>
            <item>42</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>17</id>
              <name/>
              <fileName>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>488</lineNumber>
              <contextFuncName>init</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>c:/Xilinx/Projects/attention_detect/grayScale_IP_hls</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>Mat</second>
                      </first>
                      <second>476</second>
                    </item>
                    <item>
                      <first>
                        <first>C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot/hls/hls_video_core.h</first>
                        <second>init</second>
                      </first>
                      <second>488</second>
                    </item>
                    <item>
                      <first>
                        <first>top.cpp</first>
                        <second>toGray</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>43</item>
          </oprand_edges>
          <opcode>ret</opcode>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_16">
          <Value>
            <Obj>
              <type>2</type>
              <id>26</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <const_type>4</const_type>
          <content>&lt;Undef not integral&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_17">
          <Obj>
            <type>3</type>
            <id>18</id>
            <name>toGray_Block__proc</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>13</count>
            <item_version>0</item_version>
            <item>5</item>
            <item>6</item>
            <item>7</item>
            <item>8</item>
            <item>9</item>
            <item>10</item>
            <item>11</item>
            <item>12</item>
            <item>13</item>
            <item>14</item>
            <item>15</item>
            <item>16</item>
            <item>17</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>21</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_18">
          <id>21</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>5</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_19">
          <id>23</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>6</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_20">
          <id>24</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>7</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_21">
          <id>25</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_22">
          <id>27</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>9</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>28</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>9</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>29</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>10</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>30</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>10</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>31</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>32</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>33</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>12</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>34</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>12</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>35</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>13</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>36</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>13</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>37</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>14</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>38</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>14</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>39</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>15</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>40</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>15</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>41</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>16</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>42</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>16</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>43</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>17</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_39">
        <mId>1</mId>
        <mTag>toGray_Block__proc</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>18</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_40">
      <states class_id="25" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_41">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>15</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_42">
              <id>3</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_43">
              <id>4</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_44">
              <id>5</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_45">
              <id>6</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_46">
              <id>7</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_47">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_48">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_49">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_50">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_51">
              <id>12</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_52">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_53">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_54">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_55">
              <id>16</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_56">
              <id>17</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </transitions>
    </fsm>
    <res class_id="30" tracking_level="1" version="0" object_id="_57">
      <dp_component_resource class_id="31" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_resource>
      <dp_expression_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="32" tracking_level="0" version="0">
          <first>ap_sig_bdd_42 ( or ) </first>
          <second class_id="33" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="34" tracking_level="0" version="0">
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>8</count>
        <item_version>0</item_version>
        <item>
          <first>ap_return_0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_2</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_3</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_4</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_5</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_6</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_7</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>24</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>10</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_0_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_1_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_2_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_3_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_4_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_5_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_6_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_7_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>12</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>12</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_component_map class_id="35" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="36" tracking_level="0" version="0">
      <count>13</count>
      <item_version>0</item_version>
      <item class_id="37" tracking_level="0" version="0">
        <first>5</first>
        <second class_id="38" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>6</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>7</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>8</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>9</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>10</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>11</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>12</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>13</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>14</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>15</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>16</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>17</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="39" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="40" tracking_level="0" version="0">
        <first>18</first>
        <second class_id="41" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="42" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="43" tracking_level="0" version="0">
      <count>12</count>
      <item_version>0</item_version>
      <item class_id="44" tracking_level="0" version="0">
        <first>18</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>24</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>31</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>35</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>51</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </second>
      </item>
      <item>
        <first>57</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>63</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>69</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
      <item>
        <first>75</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>15</item>
        </second>
      </item>
      <item>
        <first>81</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>16</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="46" tracking_level="0" version="0">
      <count>10</count>
      <item_version>0</item_version>
      <item class_id="47" tracking_level="0" version="0">
        <first>inMat_cols_V_fu_35</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>inMat_rows_V_fu_31</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>mrv_1_fu_45</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>mrv_2_fu_51</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </second>
      </item>
      <item>
        <first>mrv_3_fu_57</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>mrv_4_fu_63</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>mrv_5_fu_69</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
      <item>
        <first>mrv_6_fu_75</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>15</item>
        </second>
      </item>
      <item>
        <first>mrv_7_fu_81</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>16</item>
        </second>
      </item>
      <item>
        <first>mrv_fu_39</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>cols_read_read_fu_18</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>rows_read_read_fu_24</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>8</count>
      <item_version>0</item_version>
      <item>
        <first>ap_return_0</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_1</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_2</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_3</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_4</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_5</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_6</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>ap_return_7</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
    </return_ports>
    <dp_mem_port_nodes class_id="48" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="49" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="50" tracking_level="0" version="0">
        <first>cols</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>5</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>rows</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>6</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="51" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>1</first>
        <second>AXI4LiteS</second>
      </item>
      <item>
        <first>2</first>
        <second>AXI4LiteS</second>
      </item>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
