// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XTOGRAY_H
#define XTOGRAY_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xtogray_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XTogray_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XTogray;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XTogray_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XTogray_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XTogray_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XTogray_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XTogray_Initialize(XTogray *InstancePtr, u16 DeviceId);
XTogray_Config* XTogray_LookupConfig(u16 DeviceId);
int XTogray_CfgInitialize(XTogray *InstancePtr, XTogray_Config *ConfigPtr);
#else
int XTogray_Initialize(XTogray *InstancePtr, const char* InstanceName);
int XTogray_Release(XTogray *InstancePtr);
#endif

void XTogray_Start(XTogray *InstancePtr);
u32 XTogray_IsDone(XTogray *InstancePtr);
u32 XTogray_IsIdle(XTogray *InstancePtr);
u32 XTogray_IsReady(XTogray *InstancePtr);
void XTogray_EnableAutoRestart(XTogray *InstancePtr);
void XTogray_DisableAutoRestart(XTogray *InstancePtr);

void XTogray_SetCols(XTogray *InstancePtr, u32 Data);
u32 XTogray_GetCols(XTogray *InstancePtr);
void XTogray_SetRows(XTogray *InstancePtr, u32 Data);
u32 XTogray_GetRows(XTogray *InstancePtr);

void XTogray_InterruptGlobalEnable(XTogray *InstancePtr);
void XTogray_InterruptGlobalDisable(XTogray *InstancePtr);
void XTogray_InterruptEnable(XTogray *InstancePtr, u32 Mask);
void XTogray_InterruptDisable(XTogray *InstancePtr, u32 Mask);
void XTogray_InterruptClear(XTogray *InstancePtr, u32 Mask);
u32 XTogray_InterruptGetEnabled(XTogray *InstancePtr);
u32 XTogray_InterruptGetStatus(XTogray *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
