// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtogray.h"

extern XTogray_Config XTogray_ConfigTable[];

XTogray_Config *XTogray_LookupConfig(u16 DeviceId) {
	XTogray_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTOGRAY_NUM_INSTANCES; Index++) {
		if (XTogray_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTogray_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTogray_Initialize(XTogray *InstancePtr, u16 DeviceId) {
	XTogray_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTogray_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTogray_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

